# Base Python 3.12
FROM python:3.12-slim

# Diretório de trabalho
WORKDIR /app

# Copia os arquivos
COPY . /app

# Instala dependências
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN pip install gunicorn

# Expõe a porta
EXPOSE 8000

# Comando de produção com Gunicorn
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "GEMMA_CESPE_GENERATOR.wsgi:application"]
