# Generated by Django 5.2 on 2025-04-17 22:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaConhecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Nome da Área')),
            ],
            options={
                'verbose_name': 'Área de Conhecimento',
                'verbose_name_plural': 'Áreas de Conhecimento',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TentativaResposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta_ce', models.CharField(blank=True, choices=[('C', 'Certo'), ('E', 'Errado')], max_length=1, null=True, verbose_name='Resposta C/E')),
                ('resposta_discursiva', models.TextField(blank=True, null=True, verbose_name='Resposta Discursiva')),
                ('data_resposta', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Resposta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Tentativa de Resposta',
                'verbose_name_plural': 'Tentativas de Respostas',
                'ordering': ['-data_resposta'],
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CE', 'Certo/Errado'), ('DISC', 'Discursiva')], max_length=4, verbose_name='Tipo de Questão')),
                ('dificuldade', models.CharField(blank=True, choices=[('facil', 'Fácil'), ('medio', 'Médio'), ('dificil', 'Difícil')], default='medio', max_length=10, verbose_name='Nível de Dificuldade')),
                ('texto_motivador', models.TextField(blank=True, null=True, verbose_name='Texto Motivador (Discursiva)')),
                ('texto_comando', models.TextField(verbose_name='Texto da Afirmação (C/E) ou Comando (Discursiva)')),
                ('aspectos_discursiva', models.TextField(blank=True, help_text='Liste os pontos que a resposta discursiva deve cobrir.', null=True, verbose_name='Aspectos a Avaliar (Discursiva)')),
                ('gabarito_ce', models.CharField(blank=True, choices=[('C', 'Certo'), ('E', 'Errado')], max_length=1, null=True, verbose_name='Gabarito Certo/Errado')),
                ('justificativa_gabarito', models.TextField(blank=True, help_text='Explicação do porquê a afirmação C/E é certa ou errada.', null=True, verbose_name='Justificativa do Gabarito (C/E)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='generator.areaconhecimento', verbose_name='Área de Conhecimento')),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('tentativa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='generator.tentativaresposta', verbose_name='Tentativa Avaliada')),
                ('correto_ce', models.BooleanField(null=True, verbose_name='Acertou C/E?')),
                ('score_ce', models.IntegerField(null=True, verbose_name='Score C/E (+1/-1)')),
                ('nc', models.FloatField(null=True, verbose_name='Nota Conteúdo (NC)')),
                ('ne', models.IntegerField(null=True, verbose_name='Contagem Erros (NE)')),
                ('npd', models.FloatField(null=True, verbose_name='Nota Final (NPD)')),
                ('feedback_ai', models.TextField(blank=True, null=True, verbose_name='Feedback Bruto AI')),
                ('justificativa_nc_ai', models.TextField(blank=True, null=True, verbose_name='Justificativa NC (Parseada)')),
                ('comentarios_ai', models.TextField(blank=True, null=True, verbose_name='Comentários AI (Parseado)')),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Avaliação')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
            },
        ),
        migrations.AddField(
            model_name='tentativaresposta',
            name='questao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.questao', verbose_name='Questão Respondida'),
        ),
    ]
