# Generated by Django 5.2 on 2026-04-19 17:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaConhecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Nome da Área')),
            ],
            options={
                'verbose_name': 'Área de Conhecimento',
                'verbose_name_plural': 'Áreas de Conhecimento',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='BancaPCI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Banca (PCI)',
            },
        ),
        migrations.CreateModel(
            name='CargoPCI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Cargo (PCI)',
            },
        ),
        migrations.CreateModel(
            name='NivelEscolaridadePCI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Nível Escolaridade (PCI)',
            },
        ),
        migrations.CreateModel(
            name='Organizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300, unique=True)),
            ],
            options={
                'verbose_name': 'Organização',
                'verbose_name_plural': 'Organizações',
            },
        ),
        migrations.CreateModel(
            name='OrgaoPCI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Órgão (PCI)',
            },
        ),
        migrations.CreateModel(
            name='PalavraChave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=100, unique=True, verbose_name='Palavra/Tópico')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Palavra-chave',
                'verbose_name_plural': 'Palavras-chave',
                'ordering': ['texto'],
            },
        ),
        migrations.CreateModel(
            name='StatusConcurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Status de Concurso',
                'verbose_name_plural': 'Status de Concursos',
            },
        ),
        migrations.CreateModel(
            name='TipoNormaPlanalto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Lei, Decreto, Lei Complementar, Medida Provisória', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Norma (Planalto)',
                'verbose_name_plural': 'Tipos de Normas (Planalto)',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='NoticiaPCICapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('link_detalhes', models.URLField(max_length=1000, unique=True)),
                ('vagas_disponiveis', models.CharField(blank=True, max_length=100, null=True)),
                ('resumo', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('data_coleta', models.DateTimeField(auto_now_add=True)),
                ('ultima_atualizacao_coleta', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notícia da Capa (PCI)',
                'verbose_name_plural': 'Notícias da Capa (PCI)',
                'ordering': ['-data_coleta'],
                'indexes': [models.Index(fields=['link_detalhes'], name='generator_n_link_de_237d7e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProvaPCIConcurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_link_origem', models.CharField(blank=True, max_length=500, null=True)),
                ('nome_concurso_detalhado', models.CharField(blank=True, max_length=500, null=True)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('nivel_detalhado_texto', models.CharField(blank=True, max_length=100, null=True)),
                ('url_pagina_detalhes', models.URLField(max_length=1024, unique=True)),
                ('url_prova_pdf', models.URLField(blank=True, max_length=1024, null=True)),
                ('url_gabarito_pdf', models.URLField(blank=True, max_length=1024, null=True)),
                ('fonte', models.CharField(default='PCI Concursos', max_length=100)),
                ('categoria_cargo_principal_texto', models.CharField(blank=True, max_length=255, null=True)),
                ('data_coleta', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao_coleta', models.DateTimeField(auto_now=True)),
                ('banca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='generator.bancapci')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='generator.cargopci')),
                ('nivel_escolaridade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='generator.nivelescolaridadepci')),
                ('orgao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='generator.orgaopci')),
            ],
            options={
                'verbose_name': 'Prova Coletada (PCI)',
                'verbose_name_plural': 'Provas Coletadas (PCI)',
                'ordering': ['-ano', 'orgao__nome'],
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ME', 'Múltipla Escolha'), ('CE', 'Certo/Errado'), ('DISC', 'Discursiva')], default='ME', max_length=4, verbose_name='Tipo de Questão')),
                ('dificuldade', models.CharField(blank=True, choices=[('facil', 'Fácil'), ('medio', 'Médio'), ('dificil', 'Difícil')], default='medio', max_length=15, verbose_name='Nível de Dificuldade')),
                ('enunciado', models.TextField(default='', verbose_name='Enunciado / Comando da Questão')),
                ('texto_motivador', models.TextField(blank=True, null=True, verbose_name='Texto Motivador (Opcional)')),
                ('alternativa_a', models.CharField(blank=True, max_length=500, null=True, verbose_name='Alternativa A')),
                ('alternativa_b', models.CharField(blank=True, max_length=500, null=True, verbose_name='Alternativa B')),
                ('alternativa_c', models.CharField(blank=True, max_length=500, null=True, verbose_name='Alternativa C')),
                ('alternativa_d', models.CharField(blank=True, max_length=500, null=True, verbose_name='Alternativa D')),
                ('alternativa_e', models.CharField(blank=True, max_length=500, null=True, verbose_name='Alternativa E')),
                ('gabarito_me', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, null=True, verbose_name='Gabarito Múltipla Escolha')),
                ('aspectos_discursiva', models.TextField(blank=True, null=True, verbose_name='Aspectos a Avaliar (Discursiva)')),
                ('gabarito_ce', models.CharField(blank=True, choices=[('C', 'Certo'), ('E', 'Errado')], max_length=1, null=True, verbose_name='Gabarito Certo/Errado')),
                ('justificativa_gabarito', models.TextField(blank=True, null=True, verbose_name='Justificativa do Gabarito (C/E)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('gerada_por_ia_para_jogo', models.BooleanField(default=False, help_text='Indica se a questão foi gerada pela IA especificamente para um jogo.')),
                ('tempo_limite', models.PositiveIntegerField(default=20, help_text='Tempo em segundos que o jogador tem para responder.', verbose_name='Tempo Limite (segundos)')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='TentativaResposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta_ce', models.CharField(blank=True, choices=[('C', 'Certo'), ('E', 'Errado')], max_length=1, null=True, verbose_name='Resposta C/E')),
                ('resposta_me', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, null=True, verbose_name='Resposta Múltipla Escolha')),
                ('resposta_discursiva', models.TextField(blank=True, null=True, verbose_name='Resposta Discursiva')),
                ('data_resposta', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Resposta')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentativas', to='generator.questao', verbose_name='Questão Respondida')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Tentativa de Resposta',
                'verbose_name_plural': 'Tentativas de Respostas',
                'ordering': ['-data_resposta'],
                'unique_together': {('usuario', 'questao')},
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correto_ce', models.BooleanField(null=True, verbose_name='Acertou C/E?')),
                ('score_ce', models.IntegerField(null=True, verbose_name='Score C/E (+1/-1)')),
                ('correto_me', models.BooleanField(null=True, verbose_name='Acertou ME?')),
                ('score_me', models.IntegerField(null=True, verbose_name='Score ME (+1/-1)')),
                ('nc', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Nota de Conteúdo (NC)')),
                ('ne', models.IntegerField(blank=True, null=True, verbose_name='Número de Erros (NE)')),
                ('npd', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Nota Final (NPD)')),
                ('feedback_ai', models.TextField(blank=True, null=True, verbose_name='Feedback bruto da IA')),
                ('justificativa_nc_ai', models.TextField(blank=True, null=True, verbose_name='Justificativa da NC pela IA')),
                ('comentarios_ai', models.TextField(blank=True, null=True, verbose_name='Comentários adicionais da IA')),
                ('data_avaliacao', models.DateTimeField(auto_now=True, verbose_name='Data/Hora da Avaliação')),
                ('tentativa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao', to='generator.tentativaresposta', verbose_name='Tentativa Avaliada')),
            ],
            options={
                'verbose_name': 'Avaliação de Tentativa',
                'verbose_name_plural': 'Avaliações de Tentativas',
            },
        ),
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Tópico')),
                ('area_conhecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicos', to='generator.areaconhecimento', verbose_name='Área de Conhecimento')),
            ],
            options={
                'verbose_name': 'Tópico',
                'verbose_name_plural': 'Tópicos',
                'ordering': ['nome'],
                'unique_together': {('nome', 'area_conhecimento')},
            },
        ),
        migrations.AddField(
            model_name='questao',
            name='topico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='generator.topico', verbose_name='Tópico'),
        ),
        migrations.CreateModel(
            name='KahootGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Título do Quiz')),
                ('is_template', models.BooleanField(default=False, help_text='Se marcado, este é um modelo de quiz reutilizável, não um jogo ao vivo.')),
                ('pin', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('status', models.CharField(choices=[('waiting', 'Aguardando Jogadores'), ('in_progress', 'Em Andamento'), ('finished', 'Finalizado')], default='waiting', max_length=20)),
                ('current_question_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kahoot_games', to=settings.AUTH_USER_MODEL)),
                ('questoes', models.ManyToManyField(blank=True, related_name='kahoot_games', to='generator.questao')),
                ('topico_descritivo', models.ForeignKey(blank=True, help_text='Tópico que descreve o jogo (pode ser temporário)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='generator.topico')),
            ],
        ),
        migrations.CreateModel(
            name='KahootPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('score', models.IntegerField(default=0)),
                ('channel_name', models.CharField(blank=True, help_text='ID do canal do WebSocket para comunicação direta', max_length=255, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='generator.kahootgame')),
                ('user', models.ForeignKey(blank=True, help_text='Usuário logado, se aplicável', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jogador de Kahoot',
                'verbose_name_plural': 'Jogadores de Kahoot',
                'unique_together': {('game', 'nickname')},
            },
        ),
        migrations.CreateModel(
            name='ConcursoNoBrasil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vagas_disponiveis', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.URLField(max_length=1000, unique=True)),
                ('categoria_coleta', models.CharField(blank=True, help_text="UF ou 'br' da coleta", max_length=10, null=True)),
                ('data_coleta', models.DateTimeField(auto_now_add=True)),
                ('ultima_atualizacao_coleta', models.DateTimeField(auto_now=True)),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.organizacao')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='generator.statusconcurso')),
            ],
            options={
                'verbose_name': 'Concurso (ConcursosNoBrasil)',
                'verbose_name_plural': 'Concursos (ConcursosNoBrasil)',
                'ordering': ['-data_coleta', 'organizacao__nome'],
                'indexes': [models.Index(fields=['link'], name='generator_c_link_0b986c_idx'), models.Index(fields=['status', 'categoria_coleta'], name='generator_c_status__76cc88_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeiPlanalto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_ou_ementa', models.TextField(blank=True, help_text='Título completo ou ementa da norma.', null=True)),
                ('numero_norma', models.CharField(blank=True, help_text='Número da lei, decreto, etc. Ex: 14.133', max_length=100, null=True)),
                ('ano_norma', models.IntegerField(blank=True, help_text='Ano de publicação da norma. Ex: 2021', null=True)),
                ('data_publicacao', models.DateField(blank=True, help_text='Data de assinatura ou publicação da norma.', null=True)),
                ('url_original', models.URLField(help_text='URL única da norma no site do Planalto.', max_length=1024, unique=True)),
                ('texto_integral_html', models.TextField(blank=True, help_text='Conteúdo HTML da lei, se capturado.', null=True)),
                ('data_coleta', models.DateTimeField(auto_now_add=True)),
                ('ultima_verificacao_coleta', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo_norma', models.ForeignKey(blank=True, help_text='Tipo da norma (Lei, Decreto, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='generator.tiponormaplanalto')),
            ],
            options={
                'verbose_name': 'Lei do Planalto Coletada',
                'verbose_name_plural': 'Leis do Planalto Coletadas',
                'ordering': ['-ano_norma', '-data_publicacao', 'numero_norma'],
                'indexes': [models.Index(fields=['tipo_norma', 'ano_norma', 'numero_norma'], name='generator_l_tipo_no_9d8dbf_idx'), models.Index(fields=['url_original'], name='generator_l_url_ori_6ef188_idx')],
            },
        ),
    ]
