# Generated by Django on 2026-04-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='correto_me',
            field=models.BooleanField(null=True, verbose_name='Acertou ME?'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='score_me',
            field=models.IntegerField(null=True, verbose_name='Score ME (+1/-1)'),
        ),
        migrations.AddField(
            model_name='tentativaresposta',
            name='resposta_me',
            field=models.CharField(
                blank=True,
                choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')],
                max_length=1,
                null=True,
                verbose_name='Resposta Múltipla Escolha',
            ),
        ),
    ]