# Generated by Django 5.2 on 2025-04-20 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_questao_criado_por'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Nome do Tópico')),
                ('area_conhecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.areaconhecimento', verbose_name='Área de Conhecimento')),
            ],
            options={
                'verbose_name': 'Tópico',
                'verbose_name_plural': 'Tópicos',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='questao',
            name='topico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='generator.topico', verbose_name='Tópico'),
        ),
    ]
