# Generated by Django 5.2 on 2025-04-21 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_topico_questao_topico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='dificuldade',
            field=models.CharField(blank=True, choices=[('facil', 'Fácil'), ('medio', 'Médio'), ('dificil', 'Difícil')], default='medio', max_length=15, verbose_name='Nível de Dificuldade'),
        ),
    ]
