# Generated by Django 5.2 on 2025-05-06 06:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0005_palavrachave'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topico',
            options={'ordering': ['area_conhecimento__nome', 'nome'], 'verbose_name': 'Tópico', 'verbose_name_plural': 'Tópicos'},
        ),
        migrations.RemoveField(
            model_name='questao',
            name='texto_comando',
        ),
        migrations.RemoveField(
            model_name='questao',
            name='topico',
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='correto_mcq',
            field=models.BooleanField(null=True, verbose_name='Acertou MCQ?'),
        ),
        migrations.AddField(
            model_name='questao',
            name='alternativa_a',
            field=models.TextField(blank=True, null=True, verbose_name='Alternativa A'),
        ),
        migrations.AddField(
            model_name='questao',
            name='alternativa_b',
            field=models.TextField(blank=True, null=True, verbose_name='Alternativa B'),
        ),
        migrations.AddField(
            model_name='questao',
            name='alternativa_c',
            field=models.TextField(blank=True, null=True, verbose_name='Alternativa C'),
        ),
        migrations.AddField(
            model_name='questao',
            name='alternativa_d',
            field=models.TextField(blank=True, null=True, verbose_name='Alternativa D'),
        ),
        migrations.AddField(
            model_name='questao',
            name='alternativa_e',
            field=models.TextField(blank=True, null=True, verbose_name='Alternativa E'),
        ),
        migrations.AddField(
            model_name='questao',
            name='gabarito_mcq',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, null=True, verbose_name='Gabarito MCQ'),
        ),
        migrations.AddField(
            model_name='questao',
            name='texto_enunciado',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Enunciado / Comando / Afirmação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tentativaresposta',
            name='resposta_mcq',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, null=True, verbose_name='Resposta MCQ'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='aspectos_discursiva',
            field=models.TextField(blank=True, help_text='Pontos que a resposta discursiva deve cobrir.', null=True, verbose_name='Aspectos a Avaliar (Discursiva)'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='gabarito_ce',
            field=models.CharField(blank=True, choices=[('C', 'Certo'), ('E', 'Errado')], max_length=1, null=True, verbose_name='Gabarito C/E'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='justificativa_gabarito',
            field=models.TextField(blank=True, help_text='Explicação do gabarito (C/E ou MCQ).', null=True, verbose_name='Justificativa do Gabarito'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='texto_motivador',
            field=models.TextField(blank=True, null=True, verbose_name='Texto Motivador'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='tipo',
            field=models.CharField(choices=[('CE', 'Certo/Errado'), ('DISC', 'Discursiva'), ('MCQ', 'Múltipla Escolha')], max_length=4, verbose_name='Tipo de Questão'),
        ),
        migrations.AlterUniqueTogether(
            name='topico',
            unique_together={('nome', 'area_conhecimento')},
        ),
    ]
