# Generated by Django 5.2 on 2025-05-06 06:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0006_alter_topico_options_remove_questao_texto_comando_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topico',
            options={'ordering': ['nome'], 'verbose_name': 'Tópico', 'verbose_name_plural': 'Tópicos'},
        ),
        migrations.AlterUniqueTogether(
            name='topico',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='correto_mcq',
        ),
        migrations.RemoveField(
            model_name='questao',
            name='alternativa_a',
        ),
        migrations.RemoveField(
            model_name='questao',
            name='alternativa_b',
        ),
        migrations.RemoveField(
            model_name='questao',
            name='alternativa_c',
        ),
        migrations.RemoveField(
            model_name='questao',
            name='alternativa_d',
        ),
        migrations.RemoveField(
            model_name='questao',
            name='alternativa_e',
        ),
        migrations.RemoveField(
            model_name='questao',
            name='gabarito_mcq',
        ),
        migrations.RemoveField(
            model_name='questao',
            name='texto_enunciado',
        ),
        migrations.RemoveField(
            model_name='tentativaresposta',
            name='resposta_mcq',
        ),
        migrations.AddField(
            model_name='questao',
            name='texto_comando',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Texto da Afirmação (C/E) ou Comando (Discursiva)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questao',
            name='topico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='generator.topico', verbose_name='Tópico'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='aspectos_discursiva',
            field=models.TextField(blank=True, help_text='Liste os pontos que a resposta discursiva deve cobrir.', null=True, verbose_name='Aspectos a Avaliar (Discursiva)'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='gabarito_ce',
            field=models.CharField(blank=True, choices=[('C', 'Certo'), ('E', 'Errado')], max_length=1, null=True, verbose_name='Gabarito Certo/Errado'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='justificativa_gabarito',
            field=models.TextField(blank=True, help_text='Explicação do porquê a afirmação C/E é certa ou errada.', null=True, verbose_name='Justificativa do Gabarito (C/E)'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='texto_motivador',
            field=models.TextField(blank=True, null=True, verbose_name='Texto Motivador (Discursiva)'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='tipo',
            field=models.CharField(choices=[('CE', 'Certo/Errado'), ('DISC', 'Discursiva')], max_length=4, verbose_name='Tipo de Questão'),
        ),
    ]
