# Generated by Django 5.2 on 2025-05-15 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0008_comentarioquestao_questaofavorita'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questaofavorita',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='questaofavorita',
            name='questao',
        ),
        migrations.RemoveField(
            model_name='questaofavorita',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='ComentarioQuestao',
        ),
        migrations.DeleteModel(
            name='QuestaoFavorita',
        ),
    ]
