# Generated by Django 5.2 on 2025-05-23 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0009_alter_questaofavorita_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BancaPCI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CargoPCI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NivelEscolaridadePCI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrgaoPCI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProvaPCIConcurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_link_origem', models.CharField(blank=True, max_length=500, null=True)),
                ('nome_concurso_detalhado', models.CharField(blank=True, max_length=500, null=True)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('url_pagina_detalhes', models.URLField(max_length=1024, unique=True)),
                ('url_prova_pdf', models.URLField(blank=True, max_length=1024, null=True)),
                ('url_gabarito_pdf', models.URLField(blank=True, max_length=1024, null=True)),
                ('fonte', models.CharField(default='PCI Concursos', max_length=100)),
                ('categoria_cargo_principal_texto', models.CharField(blank=True, max_length=255, null=True)),
                ('data_coleta', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao_coleta', models.DateTimeField(auto_now=True)),
                ('banca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='generator.bancapci')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='generator.cargopci')),
                ('nivel_escolaridade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='generator.nivelescolaridadepci')),
                ('orgao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='generator.orgaopci')),
            ],
            options={
                'verbose_name': 'Prova Coletada (PCI)',
                'verbose_name_plural': 'Provas Coletadas (PCI)',
                'ordering': ['-ano', 'orgao__nome'],
            },
        ),
    ]
