# Generated by Django 5.2 on 2025-05-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0010_bancapci_cargopci_nivelescolaridadepci_orgaopci_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provapciconcurso',
            name='nivel_detalhado_texto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
