# Generated by Django 5.2 on 2025-05-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0011_provapciconcurso_nivel_detalhado_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargopci',
            name='nome',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
