# Generated by Django 5.2 on 2025-05-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0012_alter_cargopci_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargopci',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
