# Generated by Django 5.2 on 2025-05-25 18:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0013_alter_cargopci_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoNormaPlanalto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Lei, Decreto, Lei Complementar, Medida Provisória', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Norma (Planalto)',
                'verbose_name_plural': 'Tipos de Normas (Planalto)',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='LeiPlanalto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_ou_ementa', models.TextField(blank=True, help_text='Título completo ou ementa da norma.', null=True)),
                ('numero_norma', models.CharField(blank=True, help_text='Número da lei, decreto, etc. Ex: 14.133', max_length=100, null=True)),
                ('ano_norma', models.IntegerField(blank=True, help_text='Ano de publicação da norma. Ex: 2021', null=True)),
                ('data_publicacao', models.DateField(blank=True, help_text='Data de assinatura ou publicação da norma.', null=True)),
                ('url_original', models.URLField(help_text='URL única da norma no site do Planalto.', max_length=1024, unique=True)),
                ('texto_integral_html', models.TextField(blank=True, help_text='Conteúdo HTML da lei, se capturado.', null=True)),
                ('data_coleta', models.DateTimeField(auto_now_add=True)),
                ('ultima_verificacao_coleta', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo_norma', models.ForeignKey(blank=True, help_text='Tipo da norma (Lei, Decreto, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='generator.tiponormaplanalto')),
            ],
            options={
                'verbose_name': 'Lei do Planalto Coletada',
                'verbose_name_plural': 'Leis do Planalto Coletadas',
                'ordering': ['-ano_norma', '-data_publicacao', 'numero_norma'],
                'indexes': [models.Index(fields=['tipo_norma', 'ano_norma', 'numero_norma'], name='generator_l_tipo_no_9d8dbf_idx'), models.Index(fields=['url_original'], name='generator_l_url_ori_6ef188_idx')],
            },
        ),
    ]
