# Generated by Django 5.2 on 2025-05-25 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0014_tiponormaplanalto_leiplanalto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bancapci',
            options={'verbose_name': 'Banca (PCI)'},
        ),
        migrations.AlterModelOptions(
            name='cargopci',
            options={'verbose_name': 'Cargo (PCI)'},
        ),
        migrations.AlterModelOptions(
            name='nivelescolaridadepci',
            options={'verbose_name': 'Nível Escolaridade (PCI)'},
        ),
        migrations.AlterModelOptions(
            name='orgaopci',
            options={'verbose_name': 'Órgão (PCI)'},
        ),
        migrations.AlterField(
            model_name='cargopci',
            name='nome',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='ConcursoNoBrasil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizacao', models.CharField(max_length=300)),
                ('vagas_disponiveis', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.URLField(max_length=1000, unique=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('categoria_coleta', models.CharField(blank=True, help_text="UF ou 'br' da coleta", max_length=10, null=True)),
                ('data_coleta', models.DateTimeField(auto_now_add=True)),
                ('ultima_atualizacao_coleta', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Concurso (ConcursosNoBrasil)',
                'verbose_name_plural': 'Concursos (ConcursosNoBrasil)',
                'ordering': ['-data_coleta', 'organizacao'],
                'indexes': [models.Index(fields=['link'], name='generator_c_link_0b986c_idx'), models.Index(fields=['status', 'categoria_coleta'], name='generator_c_status_596ada_idx')],
            },
        ),
        migrations.CreateModel(
            name='NoticiaPCICapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('link_detalhes', models.URLField(max_length=1000, unique=True)),
                ('vagas_disponiveis', models.CharField(blank=True, max_length=100, null=True)),
                ('resumo', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('data_coleta', models.DateTimeField(auto_now_add=True)),
                ('ultima_atualizacao_coleta', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notícia da Capa (PCI)',
                'verbose_name_plural': 'Notícias da Capa (PCI)',
                'ordering': ['-data_coleta'],
                'indexes': [models.Index(fields=['link_detalhes'], name='generator_n_link_de_237d7e_idx')],
            },
        ),
    ]
