# Generated by Django 5.2 on 2025-06-15 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0015_alter_bancapci_options_alter_cargopci_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KahootGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(blank=True, max_length=6, unique=True)),
                ('status', models.CharField(choices=[('waiting', 'Aguardando Jogadores'), ('in_progress', 'Em Andamento'), ('finished', 'Finalizado')], default='waiting', max_length=20)),
                ('current_question_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('questoes', models.ManyToManyField(related_name='kahoot_games', to='generator.questao')),
                ('topico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.topico')),
            ],
        ),
        migrations.CreateModel(
            name='KahootPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('score', models.IntegerField(default=0)),
                ('channel_name', models.CharField(blank=True, max_length=255, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='generator.kahootgame')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('game', 'nickname')},
            },
        ),
    ]
