# Generated by Django 5.2 on 2025-06-15 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0016_kahootgame_kahootplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='gerada_por_ia_para_jogo',
            field=models.BooleanField(default=False, help_text='Indica se a questão foi gerada pela IA especificamente para um jogo.'),
        ),
    ]
