# Generated by Django 5.2 on 2025-06-15 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0017_questao_gerada_por_ia_para_jogo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300, unique=True)),
            ],
            options={
                'verbose_name': 'Organização',
                'verbose_name_plural': 'Organizações',
            },
        ),
        migrations.CreateModel(
            name='StatusConcurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Status de Concurso',
                'verbose_name_plural': 'Status de Concursos',
            },
        ),
        migrations.AlterModelOptions(
            name='concursonobrasil',
            options={'ordering': ['-data_coleta', 'organizacao__nome'], 'verbose_name': 'Concurso (ConcursosNoBrasil)', 'verbose_name_plural': 'Concursos (ConcursosNoBrasil)'},
        ),
        migrations.AlterModelOptions(
            name='kahootplayer',
            options={'verbose_name': 'Jogador de Kahoot', 'verbose_name_plural': 'Jogadores de Kahoot'},
        ),
        migrations.RenameIndex(
            model_name='concursonobrasil',
            new_name='generator_c_status__76cc88_idx',
            old_name='generator_c_status_596ada_idx',
        ),
        migrations.RemoveField(
            model_name='kahootgame',
            name='topico',
        ),
        migrations.RemoveField(
            model_name='questao',
            name='area',
        ),
        migrations.RemoveField(
            model_name='questao',
            name='texto_comando',
        ),
        migrations.AddField(
            model_name='kahootgame',
            name='topico_descritivo',
            field=models.ForeignKey(blank=True, help_text='Tópico que descreve o jogo (pode ser temporário)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='generator.topico'),
        ),
        migrations.AddField(
            model_name='questao',
            name='enunciado',
            field=models.TextField(default='', verbose_name='Enunciado / Comando da Questão'),
        ),
        migrations.AlterField(
            model_name='kahootplayer',
            name='channel_name',
            field=models.CharField(blank=True, help_text='ID do canal do WebSocket para comunicação direta', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kahootplayer',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Usuário logado, se aplicável', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questao',
            name='aspectos_discursiva',
            field=models.TextField(blank=True, null=True, verbose_name='Aspectos a Avaliar (Discursiva)'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='justificativa_gabarito',
            field=models.TextField(blank=True, null=True, verbose_name='Justificativa do Gabarito (C/E)'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='texto_motivador',
            field=models.TextField(blank=True, null=True, verbose_name='Texto Motivador (Opcional)'),
        ),
        migrations.AlterField(
            model_name='topico',
            name='area_conhecimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicos', to='generator.areaconhecimento', verbose_name='Área de Conhecimento'),
        ),
        migrations.AlterField(
            model_name='topico',
            name='nome',
            field=models.CharField(max_length=150, verbose_name='Nome do Tópico'),
        ),
        migrations.AlterUniqueTogether(
            name='topico',
            unique_together={('nome', 'area_conhecimento')},
        ),
        migrations.AlterField(
            model_name='concursonobrasil',
            name='organizacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.organizacao'),
        ),
        migrations.AlterField(
            model_name='concursonobrasil',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='generator.statusconcurso'),
        ),
    ]
