# Generated by Django 5.2 on 2025-06-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0018_organizacao_statusconcurso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='tempo_limite',
            field=models.PositiveIntegerField(default=20, help_text='Tempo em segundos que o jogador tem para responder.', verbose_name='Tempo Limite (segundos)'),
        ),
    ]
