# Generated by Django 5.2 on 2025-06-16 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0019_questao_tempo_limite'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='alternativa_a',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Alternativa A'),
        ),
        migrations.AddField(
            model_name='questao',
            name='alternativa_b',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Alternativa B'),
        ),
        migrations.AddField(
            model_name='questao',
            name='alternativa_c',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Alternativa C'),
        ),
        migrations.AddField(
            model_name='questao',
            name='alternativa_d',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Alternativa D'),
        ),
        migrations.AddField(
            model_name='questao',
            name='alternativa_e',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Alternativa E'),
        ),
        migrations.AddField(
            model_name='questao',
            name='gabarito_me',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, null=True, verbose_name='Gabarito Múltipla Escolha'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='tipo',
            field=models.CharField(choices=[('ME', 'Múltipla Escolha'), ('CE', 'Certo/Errado'), ('DISC', 'Discursiva')], default='ME', max_length=4, verbose_name='Tipo de Questão'),
        ),
    ]
