# Generated by Django 5.2 on 2025-06-16 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0020_questao_alternativa_a_questao_alternativa_b_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kahootgame',
            name='is_template',
            field=models.BooleanField(default=False, help_text='Se marcado, este é um modelo de quiz reutilizável, não um jogo ao vivo.'),
        ),
        migrations.AddField(
            model_name='kahootgame',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Título do Quiz'),
        ),
        migrations.AlterField(
            model_name='kahootgame',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kahoot_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kahootgame',
            name='pin',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='kahootgame',
            name='questoes',
            field=models.ManyToManyField(blank=True, related_name='kahoot_games', to='generator.questao'),
        ),
    ]
